# fly.toml app configuration file generated for trip-meister on 2025-02-04T19:46:52Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'trip-meister'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
