/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as ServerSideImport } from "./routes/server-side";
import { Route as IndexImport } from "./routes/index";

// Create/Update Routes

const ServerSideRoute = ServerSideImport.update({
	id: "/server-side",
	path: "/server-side",
	getParentRoute: () => rootRoute,
} as any);

const IndexRoute = IndexImport.update({
	id: "/",
	path: "/",
	getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
	interface FileRoutesByPath {
		"/": {
			id: "/";
			path: "/";
			fullPath: "/";
			preLoaderRoute: typeof IndexImport;
			parentRoute: typeof rootRoute;
		};
		"/server-side": {
			id: "/server-side";
			path: "/server-side";
			fullPath: "/server-side";
			preLoaderRoute: typeof ServerSideImport;
			parentRoute: typeof rootRoute;
		};
	}
}

// Create and export the route tree

export interface FileRoutesByFullPath {
	"/": typeof IndexRoute;
	"/server-side": typeof ServerSideRoute;
}

export interface FileRoutesByTo {
	"/": typeof IndexRoute;
	"/server-side": typeof ServerSideRoute;
}

export interface FileRoutesById {
	__root__: typeof rootRoute;
	"/": typeof IndexRoute;
	"/server-side": typeof ServerSideRoute;
}

export interface FileRouteTypes {
	fileRoutesByFullPath: FileRoutesByFullPath;
	fullPaths: "/" | "/server-side";
	fileRoutesByTo: FileRoutesByTo;
	to: "/" | "/server-side";
	id: "__root__" | "/" | "/server-side";
	fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
	IndexRoute: typeof IndexRoute;
	ServerSideRoute: typeof ServerSideRoute;
}

const rootRouteChildren: RootRouteChildren = {
	IndexRoute: IndexRoute,
	ServerSideRoute: ServerSideRoute,
};

export const routeTree = rootRoute
	._addFileChildren(rootRouteChildren)
	._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/server-side"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/server-side": {
      "filePath": "server-side.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
